spring:
  application:
    name: AccessOne-backend

  datasource:
    url: jdbc:mysql://localhost:3306/AccessOne?useSSL=false&serverTimezone=Asia/Colombo&allowPublicKeyRetrieval=true
    username: AccessOne_app
    password: ChangeThisPassword123!

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration

server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: health

logging:
  level:
    org.hibernate.SQL: debug